zhblue/hustoj

- wiki/HUSTOJ_LiveCD.wiki
only baidu download link work~
> Remove disabled download url

- trunk/web/template/classic/submitpage.php
第238行 是 window.clearInterval() 不是  window.cleanInterval
加了intervalId會比較明確
檢查一下其他的template有沒有這個問題
> 您的Code打的太急了，测试运行秒數越跑越快

- trunk/install/install_judge_systemd.sh
- trunk/install/judged.service
install
->judged.service
->install_judge_systemd.sh
> 添加支持ubuntu16.04的新管理系统systemd的启动服务脚本

- trunk/core/judge_client/judge_client.cc
Avoid Compiler Bomb like:
int main() {
struct x struct z<x(x(x(x(x(x(x(x(x(x(x(x(x(x(x(y,x(y><y*,x(y*w>v<y*,w,x{}
return 0; 
}
> Avoid Compiler Bomb

- .gitignore
- trunk/web/admin/contest_list.php
- trunk/web/admin/index.php
- trunk/web/admin/kindeditor.php
- trunk/web/admin/privilege_list.php
- trunk/web/admin/problem_list.php
Modifying admin menu pages... :)
> admin menu pages improving~

- trunk/web/admin/problem_add_page.php
- trunk/web/problem.php
- trunk/web/template/bs3/problem.php
modified designs? in the codes related to problem registration/view.
and
rearranged the php set's codes... and adjusted them. with some fix.
:)
> problem registration... pages..

- trunk/web/lang/ko.php
> korean translation fix

- trunk/web/lang/ko.php
- trunk/web/template/bs3/profile.php
reg_info
userinfo
submissions
contests
...
> navbar-right(profile) adjustment

- trunk/web/template/bs3/modifypage.php
reg_info page renewaling. tuned like regisration page.
> modifypage.php renewal

- trunk/web/admin/problem_add.php
- trunk/web/admin/problem_add_page.php
- trunk/web/admin/problem_edit.php
- trunk/web/problem.php
- trunk/web/template/bs3/problem.php
- problem_edit.php(problem edit page) tuned like regstration page
with
- fixing KindEditor's auto <p>...</p> tags...
<p>...</p> tag changed to  ...<br />
- problem description
- input description
- output description
- hint
...
> problem add & edit adjustment

- trunk/web/admin/help.php
- trunk/web/admin/menu.php
- trunk/web/lang/ko.php
set login ip menu & link fix..
+ ko $msg_set_loin_ip
> set login ip menu fix

- trunk/web/admin/contest_add.php
- trunk/web/admin/contest_edit.php
- trunk/web/admin/problem_add.php
- trunk/web/admin/problem_edit.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/ko.php
contest add & edit page renewal
- with some fix...
- and interface rearrangement
> contest add & edit renewal~

- trunk/web/admin/news_add.php
- trunk/web/admin/news_add_page.php
- trunk/web/admin/news_edit.php
- trunk/web/admin/setmsg.php
- news-add, news-edit page adjustment
- setmsg kindeditor character input fix
~ thank you :)
> news add & edit + kindeditor fix

- trunk/web/admin/contest_add.php
- trunk/web/admin/contest_edit.php
- trunk/web/admin/contest_list.php
- trunk/web/admin/news_add_page.php
- trunk/web/admin/news_list.php
- trunk/web/contest.php
- news list : search & copy function~
- contest list : .. some adjustment & fix
- contest.php : ... code line up for later work?
:) thank you~
> news list improvement + etc

- trunk/web/admin/contest_add.php
- trunk/web/admin/contest_list.php
- trunk/web/admin/news_list.php
- trunk/web/admin/privilege_list.php
- trunk/web/admin/problem_df_change.php
- trunk/web/admin/problem_list.php
- trunk/web/admin/user_list.php
- contest_add ... title add : "-Copy"
- contest_list pagenation remake~
- news_list pagination remake~
- privilege_list pagination remake~
- problem_list pagination remake~
+ batch function..fix?
- user_list pagination remake~
:)
> ...list pages... paginations

- trunk/web/submitpage.php
forbid enter the page that not exsit problem
> submitpage.php bug

- trunk/web/template/bs3/scrollboard.js
在3500毫秒后重新调整了滚动条位置，会导致滚榜时页面一上一下跳动。此部分代码还原为滚榜插件原作者代码，bug得到修复
> recover ScrollBoard some codes

- trunk/web/template/bs3/scrollboard.js
fit for 200+ people in a short time on site.
> speed up the scrollboard for contest on site . 

- trunk/install/install-centos7.sh
- trunk/install/install-ubuntu16-bytgz.sh
- trunk/install/install-ubuntu18-bytgz.sh
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/template/ace/loginpage.php
- trunk/web/template/bs/loginpage.php
- trunk/web/template/classic/loginpage.php
- trunk/web/template/ie/loginpage.php
- trunk/web/template/sae/loginpage.php
修改了USERINFO与ModifyUser之间的歧义，因为在profile.php中发现/modifyuser.php的i18n为“注册信息”而/userinfo.php?的i18n为“修改用户”，感觉产生了上下文歧义
> Update lang/cn.php and lang/en.php

- trunk/install/db.sql
- trunk/web/admin/update_db.php
- trunk/web/include/db_info.inc.php
- trunk/web/sharecodelist.php
- trunk/web/sharecodepage.php
- trunk/web/template/bs3/profile.php
- trunk/web/template/bs3/sharecodelist.php
- trunk/web/template/bs3/sharecodepage.php
1. Added share_code table.
2. Add two pages, one is the list page, the other is the display page.
3. Add `$OJ_SHARE_CODE` to `db_info.inc.php`.
4. Add entrance to `Code Sharing` on the `bs3/profile.php`
5. Modified `install/db.sql`  and  `admin/update_db.php`
> Increase the function of Code Sharing.

- trunk/install/default.conf
- trunk/install/install+.sh
- trunk/install/install-centos7.sh
> Create HUSTOJ virtual server without modification of nginx.conf

- trunk/core/judge_client/judge_client.cc
> Fix python support in Centos7

- trunk/install/install-ubuntu14-bytgz.sh
- trunk/install/install-ubuntu14.04.sh
- trunk/install/install-ubuntu16+.sh
- trunk/install/install-ubuntu16-bytgz.sh
- trunk/install/install-ubuntu18-bytgz.sh
- trunk/install/install-ubuntu18.04.sh
- trunk/web/recent-contest.php
- trunk/web/template/bs3/recent-contest.php
- trunk/web/template/ie/recent-contest.php
- trunk/web/template/sweet/recent-contest.php
更改名校联赛实现方法，采用nginx反向代理+js渲染表格实现（仅限bs3,ie,sweet三个模板）。
> 更改名校联赛实现方法

- trunk/web/template/ace/lostpassword.php
- trunk/web/template/bs/lostpassword.php
- trunk/web/template/bs3/lostpassword.php
- trunk/web/template/classic/lostpassword.php
- trunk/web/template/ie/lostpassword.php
- trunk/web/template/sae/lostpassword.php
- trunk/web/template/sweet/lostpassword.php
> 修复找回密码页面，验证码点击不刷新的bug

- trunk/web/problemset.php
> 题目列表的标签增加title属性

- .travis.yml
ubuntu 18 镜像来自 https://github.com/muzea/hustoj-deb-ubuntu18
debian 8 镜像来自 https://github.com/muzea/hustoj-deb-debian8
> feat: deb打包

- Dockerfile
make 'run${}' work directory to judge without shm
> Fix unknown WA and RE in SHM filesystem.

- trunk/web/include/db_info.inc.php
- trunk/web/submit.php
https://github.com/muzea/hustoj/blob/feature/benchmark_mode_rebase/trunk/web/submit.php#L14-L41
https://github.com/muzea/hustoj/blob/feature/benchmark_mode_rebase/trunk/web/submit.php#L221-L233
https://github.com/muzea/hustoj/blob/feature/benchmark_mode_rebase/trunk/web/submit.php#L300-L303
主要三处修改，代码格式化使用 `prettier`。
> feat: benchmark mode

- .travis.yml
> fix: gitee 过慢导致超时

- trunk/web/include/login-hustoj.php
Who could fingure new ip if administrator is denied?
> Allow administrator to multi-ip login

- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/template/bs3/faqs.ko.php
major fix:
Translations...
- en.php
- fa.php
- ko.php
- th.php
- ug.php
modified in accordance with cn.php
Thanks zhblue. :)
> Translations modified in accordance with cn.php

- trunk/web/admin/menu2.php
- trunk/web/lang/ko.php
- trunk/web/template/bs3/faqs.ko.php
Left admin menu2 reorganizing~.
+ little korean fix
Thanks zhblue.
> Left admin menu2 reorganizaing.

- trunk/web/admin/help.php
- trunk/web/admin/menu2.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
Fix and reorganizing admin page.
Thanks~ :)
> Fix and reorganizing admin page

- trunk/web/index.php
index.php fix for faqs.xx
Thanks ~:)
> index.php fix for faqs.xx

- trunk/web/status-ajax.php
- trunk/web/status.php
- trunk/web/template/ace/status.php
- trunk/web/template/bs/status.php
- trunk/web/template/bs3/status.php
- trunk/web/template/bs3/submitpage.php
- trunk/web/template/classic/status.php
- trunk/web/template/ie/status.php
- trunk/web/template/sae/status.php
- trunk/web/template/sweet/status.php
fix status view...
+
submitpage realign.
Thank you :)
> Some fix status.php ... +

- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/template/bs3/problemset.php
- trunk/web/template/bs3/status.php
- trunk/web/template/bs3/submitpage.php
> Delete duplicated MSG_USER

- trunk/web/contest.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/template/bs3/contest.php
- trunk/web/template/bs3/contestset.php
some fix for contest
Thank you. :)
> some fix for contest

- trunk/web/admin/news_list.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/template/bs3/faqs.cn.php
- trunk/web/template/bs3/faqs.ko.php
- trunk/web/template/bs3/faqs.ug.php
- removed... default text about faqs.xx
- added... to admin's news_list menu
Thank you :)
> Some fix to faqs.xx

- trunk/web/contest.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/template/bs3/contestrank-oi.php
- trunk/web/template/bs3/contestset.php
- Contest fix :
private password
before contest
> Contest fix~

- trunk/web/contest.php
- trunk/web/index.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/status.php
- trunk/web/template/bs3/contest.php
- trunk/web/template/bs3/conteststatus.php
- trunk/web/template/bs3/js.php
- trunk/web/template/bs3/status.php
- Moved HUSTOJ Github Star message from News To footer.
+ made %MSG_HELP_HUSTOJ for other languages.
It would be more efficient~
- Made ... $MSG_JUDGER for only admin.
ex) status page
Thank you :)
> Rearranged HUSTOJ Github Star message

- trunk/web/include/db_info.inc.php
> add template of mario

- trunk/web/category.php
- trunk/web/lang/ko.php
- trunk/web/template/bs3/problem.php
- problem page check & re-aligning...
Thank you.
> problem page re-aligning

- trunk/web/category.php
- trunk/web/template/bs3/category.php
- trunk/web/template/bs3/contest.php
- trunk/web/template/bs3/contestset.php
- trunk/web/template/bs3/conteststatus.php
- trunk/web/template/bs3/js.php
- trunk/web/template/bs3/problem.php
- trunk/web/template/bs3/problemset.php
- trunk/web/template/bs3/status.php
- trunk/web/template/bs3/submitpage.php
- problem page : button inserted & rearranging
- category page : resizing & rearranging
Thank you~:)
> problem.php

- trunk/web/admin/contest_add.php
- trunk/web/admin/contest_edit.php
- trunk/web/admin/contest_list.php
- trunk/web/admin/help.php
- trunk/web/admin/menu2.php
- trunk/web/admin/news_add_page.php
- trunk/web/admin/news_edit.php
- trunk/web/admin/news_list.php
- trunk/web/admin/privilege_list.php
- trunk/web/admin/problem_add_page.php
- trunk/web/admin/problem_edit.php
- trunk/web/admin/problem_list.php
- trunk/web/admin/setmsg.php
- trunk/web/admin/user_list.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
> Some Adjustments~

- trunk/web/admin/admin-header.php
- trunk/web/admin/changepass.php
- trunk/web/admin/help.php
- trunk/web/admin/menu2.php
- trunk/web/admin/setmsg.php
- trunk/web/admin/user_list.php
- trunk/web/template/bs3/js.php
- trunk/web/template/bs3/profile.php
- Fix password_setter
- fix password_setter's admin menu
- Improvement to resetting password
- resetting password is possible through user_list for admin and password_setter
- of course, it is possible.. with original menu too.
+ some adjustments.
Thank you :)
> Password changing improvement~

- trunk/web/status.php
- trunk/web/template/bs3/status.php
- code cleanup
- status.php
+ little adjustment
> Code cleanup

- trunk/web/bsadmin/problem_export.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/modify_info.php
- trunk/web/template/bshark/contest.php
- trunk/web/template/bshark/contestrank-oi.php
- trunk/web/template/bshark/contestrank.php
- trunk/web/template/bshark/contestset.php
- trunk/web/template/bshark/conteststatistics.php
- trunk/web/template/bshark/index.php
- trunk/web/template/bshark/loginpage.php
- trunk/web/template/bshark/main.css
- trunk/web/template/bshark/modifypage.php
- trunk/web/template/bshark/nav.php
- trunk/web/template/bshark/problem.php
- trunk/web/template/bshark/problemset.php
- trunk/web/template/bshark/ranklist.php
- trunk/web/template/bshark/registerpage.php
- trunk/web/template/bshark/status.php
- trunk/web/template/bshark/submitpage.php
- trunk/web/template/bshark/userinfo.php
- trunk/web/template/bshark/viewnews.php
前端所有显示内容用MSG显示
增加 `$MSG_EDIT` 和 `$MSG_TESTDATA` 两项用于问题页面显示
修复了已知的bug。目前还有contestrank2和3，balloon和codeshare没有完成
后端内容预计后天完成
> 前端使用MSG显示内容，并且修复部分bug

- trunk/web/contest.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/submit.php
- trunk/web/template/bs3/contest.php
- Translation for submit.php
- ended contest's problem's link to normal practice
> Translation for submit.php +

- trunk/web/bsadmin/contest_edit.php
- trunk/web/bsadmin/nav.php
- trunk/web/bsadmin/update_db.php
- trunk/web/bsadmin/user_edit.php
原本在contest表中加了type字段区分acm和oi，因为hustoj没有此功能。
原本在users表里面加了 壕币 和 积分，也去掉了，修复了这类问题
增加了update_db.php
> 修复bsadmin的部分bug，补充了功能

- trunk/web/contestrank-oi.php
- trunk/web/conteststatistics.php
- trunk/web/status.php
- trunk/web/template/bs3/contestrank-oi.php
- trunk/web/template/bs3/contestrank.php
- trunk/web/template/bs3/conteststatistics.php
- trunk/web/template/bs3/conteststatus.php
- trunk/web/template/bs3/problemset.php
- trunk/web/template/bs3/ranklist.php
- trunk/web/template/bs3/status.php
> Contest bug fix + improvement + etc

- trunk/web/admin/suspect_list.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/suspect_list.php
- trunk/web/template/bs3/contestrank-oi.php
- trunk/web/template/bs3/contestrank.php
- trunk/web/template/bs3/conteststatistics.php
- trunk/web/template/bs3/conteststatus.php
- trunk/web/template/bs3/suspect_list.php
> Suspect list improvement

- trunk/web/template/bshark/faqs.cn.php
- trunk/web/template/bshark/faqs.php
- trunk/web/template/bshark/footer.php
- trunk/web/template/bshark/index.php
- trunk/web/template/bshark/nav.php
1. 增加了`faqs.php`和`faqs.cn.php`
2. 在首页添加了公众号 和 红包 的 二维码（想让底部简洁一点）
3. 修复了已知的bug
> 更新 #2020021201

- trunk/web/admin/suspect_list.php
- trunk/web/suspect_list.php
- trunk/web/template/bs3/contest.php
- trunk/web/template/bs3/contestrank-oi.php
- trunk/web/template/bs3/contestrank.php
- trunk/web/template/bs3/conteststatistics.php
- trunk/web/template/bs3/conteststatus.php
- trunk/web/template/bs3/suspect_list.php
- trunk/web/template/bs3/user_set_ip.php
- trunk/web/user_set_ip.php
- user_set_ip menu added at contest for admin
- time added at suspect_list 
Thank you :)
> user_set_ip, suspect_list

- trunk/web/contest.php
- trunk/web/problem.php
- trunk/web/problemset.php
- Problems that will be use ramained contest/exam hidden in past contest's problem list
Problems not used in all the other remained contest will be shown normally.
- defuncted (in problem table) problem can be use in contest/exam
- but, can't be access in practice mode
> Contest Improvement

- trunk/web/bsadmin/contest_add.php
- trunk/web/bsadmin/contest_edit.php
- trunk/web/bsadmin/contest_list.php
- trunk/web/bsadmin/nav.php
- trunk/web/template/bshark/main-dark.css
1. 修复了后台nav文字无法正常显示的问题
2. dark主题所有card开启反色，颜色更鬼畜
3. 后台部分文字用MSG替换
> 修复了后台nav文字无法正常显示的问题

- trunk/web/lang/ko.php
- trunk/web/template/bs3/contest.php
- trunk/web/template/bs3/contestrank-oi.php
- trunk/web/template/bs3/contestrank.php
- trunk/web/template/bs3/conteststatistics.php
- trunk/web/template/bs3/conteststatus.php
- trunk/web/template/bs3/suspect_list.php
- trunk/web/template/bs3/user_set_ip.php
contest admin menu improvement
> contest admin menu improvement

- trunk/web/admin/problem_add.php
- trunk/web/admin/problem_add_page.php
- trunk/web/admin/problem_del.php
- trunk/web/admin/problem_df_change.php
- trunk/web/admin/problem_edit.php
- trunk/web/admin/problem_import.php
- trunk/web/admin/problem_list.php
- trunk/web/problem.php
- trunk/web/template/bs3/problem.php
- Fix for probel_editor privilege
- problem_add
- problem_del
- problem_df_change
- problem_edit
- problem_import
- problem_export
- problem_list
> Fix for problem_editor privilege

- trunk/web/admin/contest_df_change.php
- trunk/web/admin/contest_edit.php
- trunk/web/admin/contest_list.php
- trunk/web/admin/contest_pr_change.php
- trunk/web/admin/help.php
- trunk/web/admin/menu2.php
- trunk/web/admin/problem_del.php
- trunk/web/admin/problem_df_change.php
- trunk/web/admin/problem_edit.php
- trunk/web/admin/problem_export.php
- trunk/web/admin/problem_export_xml.php
- trunk/web/admin/problem_import.php
- trunk/web/admin/problem_list.php
- trunk/web/admin/team_generate.php
- trunk/web/admin/team_generate2.php
- trunk/web/export_contest_code.php
- trunk/web/user_set_ip.php
- Fix for contest_creator privilege
- ...
:)
Thank you.
> Fix for contest_creator privilege

- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/template/mario/ranklist.php
update ranklist.php's UI and MUSHROOMS ADDED!!!
Thank you :)
> add mushrooms to ranklist.php 

- trunk/web/template/mario/oj-footer.php
- trunk/web/template/mario/oj-header.php
- trunk/web/template/mario/swProfile.php
swProfile and login fixed please test.
@zhblue    Thank you :)
> fixing swProfile

- trunk/web/template/mario/ranklist.php
mushrooms too much! minus some.
@zhblue   Thank you :)
> mushrooms too much!

- trunk/web/template/bshark/index.php
- trunk/web/template/bshark/main-dark.css
- trunk/web/template/bshark/main-light.css
- trunk/web/template/bshark/nav.php
- trunk/web/template/bshark/theme.conf.php
主题配置文件新增`$THEME_BANNER`
改成hidden之后能够隐藏
> 能够隐藏掉Banner

- trunk/web/template/bs3/blue.css
- trunk/web/template/bs3/problem.php
> fix submit count

- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/mail.php
add the single error output for OJ_MAIL=false 
@zhblue 
:)))          (三下巴)(逃ε=ε=ε=┏(゜ロ゜;)┛
> Some addition~~

- trunk/web/template/mario/ranklist.php
fix the mushrooms and let them show off in a better way~
Thank you :)))                (三下巴)(逃ε=ε=ε=┏(゜ロ゜;)┛
> update ranklist.php's mushroomes for Mario temp.

- README.md
> 修改Ubuntu18.04更换软件源方法的链接

- README.md
有个表格没写表头
另外把更新日志按年写出来了（不过显示的问题貌似没有解决）
: ）
> 修复README.md显示异常的问题

- README.md
- trunk/core/judge_client/okcalls64.h
- trunk/install/install+.sh
- trunk/install/install-ubuntu20.04.sh
Install script was tested, there is nothing wrong when A+B with C/C++/Pascal/Java/Bash/Python/C#
> Adjust install script for Ubuntu 20.04 LTS(Focal)

- trunk/web/bsadmin/index.php
- trunk/web/template/bshark/index.php
- trunk/web/template/bshark/theme.conf.php
- trunk/web/template/bshark/userinfo.php
使用gravatar显示头像，而不是原来我自己的qq头像
修复了部分问题
> 使用gravatar显示头像

- wiki/A+B.md
add some colors to your code
Thank you:)
> add some colors to your code

- trunk/web/login.php
如果cookie错误/失效 则 删除cookie,保证index/loginpage页面不发生loooooooop:)
Thank you:)
> cookie登录死循环修复

- trunk/web/status.php
- trunk/web/template/bs3/auto_refresh.js
- trunk/web/template/bs3/status.php
- trunk/web/template/bs3/submitpage.php
- status.php AC ratio print fix
- results printed with AC ratio for partial WA
- but it printed AC ratio for only own ID and source_brower ID
> status.php AC ratio print fix

- trunk/core/judge_client/okcalls64.h
- trunk/web/reinfo.php
- trunk/web/status.php
- trunk/web/template/bs3/reinfo.php
- Update okcalls64.h fix for python judging~
- added : SYS_getuid
- renamed : 318 -> SYS_getrandom
> okcalls64.h fix for python judging~

- trunk/web/lang/ko.php
Co-authored-by: PMH <pmhstudio.pmh@gmail.com>
> Korean translate

- trunk/web/lang/ko.php
- trunk/web/template/bs3/faqs.ko.php
> korean interface improvement

- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
> 联动NOIP提示关键字

- trunk/core/judge_client/okcalls32.h
- trunk/core/judge_client/okcalls64.h
c/c++ compile error fix for ubuntu20.04
> c/c++ compile error fix for ubuntu20.04

- trunk/core/judge_client/okcalls64.h
- trunk/web/lang/ko.php
- trunk/web/template/bs3/faqs.ko.php
fix for C/C++ recursion function enable!
Ubuntu 20.04 LTS
> fix for recursion enable!

- trunk/web/template/bs3/contestrank-oi.php
- trunk/web/template/bs3/contestrank.php
- trunk/web/template/bs3/conteststatistics.php
- trunk/web/template/bs3/suspect_list.php
contest modification&fix
todo : ... hmm... there is problem lock error... i will fix... soon.
> contest modification&fix

- trunk/web/problemstatus.php
- trunk/web/template/bs3/conteststatistics.php
- trunk/web/template/bs3/problemstatus.php
conteststatistics, problesstatus page updates
> conteststatistics, problesstatus page updates

- trunk/web/admin/problem_add.php
- trunk/web/admin/problem_add_page.php
- trunk/web/admin/problem_edit.php
- trunk/web/admin/problem_export.php
- trunk/web/admin/problem_export_xml.php
- trunk/web/admin/problem_import.php
- trunk/web/admin/problem_import_xml.php
- trunk/web/include/problem.php
> problem export/import updates

- trunk/web/admin/problem_export_xml.php
xml data sorting ascending order
by file name
with default scandir( ) function
:)
> xml data sorting ascending order

- trunk/core/judge_client/okcalls64.h
fix for python OJ_SHOW_DIFF error
Thank you~ :)
> for python OJ_SHOW_DIFF

- trunk/core/judge_client/okcalls64.h
C/C++ TLE error SHOW_DIFF fix~
Thank you~ :)
> For C/C++ TLE error SHOW_DIFF fix

- trunk/web/admin/user_list.php
> fix typo :)

- trunk/web/template/bs3/nav.php
学校最近在做网络安全建设，把这个注释错误扫成源码泄露漏洞了😂。
> Fix: unexpected comment error

- trunk/web/problemset.php
Previously, the navigator counted the number of reserved problems. Now show 50 problem excluding reserved ones.
> Change Problemset.php's  Page Navigator

- trunk/web/template/bshark/header-files.php
- trunk/web/template/bshark/main-light.css
- trunk/web/template/bshark/nav.php
- trunk/web/template/bshark/problem.php
- trunk/web/template/bshark/problemset.php
- trunk/web/template/bshark/ranklist.php
- trunk/web/template/bshark/status.php
- trunk/web/template/bshark/submitpage.php
- trunk/web/template/bshark/theme.conf.php
- 修改problemset.php，不再使用Y和N的按钮，而是当前行最左端的颜色表示通过情况
- 修改problem.php，更改复制按钮样式，提交等按钮样式，题目信息样式
- 修改背景颜色，阴影
- 更多
> 更新bshark界面

- trunk/web/template/syzoj/error.php
> add some notes.

- trunk/web/template/bs3/nav.php
- remaking code indentation
- bs3 template's nav bar width size error fix
> bs3 nav bar width size error fix

- trunk/web/admin/phpfm.php
- trunk/web/admin/problem_add_page.php
- trunk/web/admin/problem_edit.php
- trunk/web/admin/problem_list.php
- trunk/web/include/bbcode.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/problemstatus.php
- trunk/web/status.php
- trunk/web/template/bs3/nav.php
- trunk/web/template/bs3/problem.php
- trunk/web/template/bs3/submitpage.php
- all translations synchronized to cn.php
- add some translation-holders for problem_list.php
- fix for korean
- add some translation-holders for bbcode.php
- add korean translation for "show off"
- ace editor cursor behaves error fix
> 22.02.17 all translations synchronized to cn.php + etc

- trunk/install/db.sql
- trunk/web/admin/news_add.php
- trunk/web/admin/news_add_page.php
- trunk/web/admin/news_edit.php
- trunk/web/admin/news_list.php
- trunk/web/admin/update_db.php
- trunk/web/include/db_info.inc.php
- trunk/web/lang/cn.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/template/syzoj/header.php
- trunk/web/viewnews.php
> [Feature] 支持把公告展示到顶栏

- trunk/web/template/syzoj/css/style.css
- trunk/web/template/syzoj/header.php
- trunk/web/template/syzoj/problem.php
> SYZOJ 主题打印样式适配

- trunk/web/template/bs3/error.php
- trunk/web/template/bs3/nav.php
- fixed nav.php menu width 98%
> bs3 nav.php fix

- trunk/web/template/bs3/problem.php
Adding upper margin for bs3 nav.php at bs3 problem.php
before
after
> Adding upper margin for bs3 nav.php at problem.php

- trunk/web/ranklist.php
> 取消排行榜中的管理员

- trunk/web/include/db_info.inc.php
- trunk/web/include/my_func.inc.php
- trunk/web/template/syzoj/index.php
allow show some news content on index of syzoj
default title "HelloWorld!"
can be set in db_info.inc.php
> Hello world syzoj

- trunk/web/template/syzoj/problem.php
> 更新syzoj主题题目未公开显示异常

- trunk/web/template/syzoj/lostpassword.php
- trunk/web/template/syzoj/lostpassword2.php
syzoj找回密码界面更新为syzoj主题的的header之前是bs3的菜单
> syzoj找回密码界面更新为syzoj主题的的header

- trunk/install/install-ubuntu-bt.sh
chattr +i /www/server/panel/script/site_task.py
chattr +i -R /www/server/panel/logs/request
> # 解决宝塔收集用户信息问题

- trunk/web/include/email.class.php
> update email.class.php's construct function

- trunk/web/admin/menu2.php
- trunk/web/lang/cn.php
> update cn.php（tk += 50）

- trunk/web/include/db_info.inc.php
- trunk/web/template/syzoj/header.php
- trunk/web/template/syzoj/problem.php
> 为oj加入背景毛玻璃特效，在配置文件中自定义背景图片链接

- trunk/web/admin/menu2.php
- trunk/web/daochu.php
> 管理员后台加入导出站点所有排行榜到表格功能

- trunk/web/include/db_info.inc.php
- trunk/web/submit.php
> Poison robots

- trunk/web/template/syzoj/problemset.php
> problemset界面修改。美化右侧解决/提交	通过率变为进度条

- Dockerfile
- docker/entrypoint.sh
- docker/setup.sh
docker相关修改，使docker能正常使用。
https://www.cnblogs.com/shiningrise/p/17460255.html
> “修改：docker想关修改，使docker能正常使用”

- trunk/web/template/syzoj/contestrank-oi.php
- trunk/web/template/syzoj/contestrank.php
- trunk/web/template/syzoj/contestrank4.php
- trunk/web/template/syzoj/contestrank5.php
Fixed an issue where style tags were being written as sylye tags
> Fixing style tag typos

- trunk/web/submit.php
I am really sorry that I did not modify the base64 function in submit.php due to my negligence.
> Fix the broken submission func

- trunk/web/bbs.php
- trunk/web/discuss.php
- trunk/web/lang/cn.php
- trunk/web/lang/cnt.php
- trunk/web/lang/en.php
- trunk/web/lang/fa.php
- trunk/web/lang/ko.php
- trunk/web/lang/ru.php
- trunk/web/lang/th.php
- trunk/web/lang/ug.php
- trunk/web/newpost.php
- trunk/web/post.php
- trunk/web/template/bs3/discuss.php
- trunk/web/template/bs3/nav.php
- trunk/web/thread.php
- trunk/web/threadadmin.php
discuss3 thread for bs3
------
- code indentations...
- checked and rebuilded discuss3 for bs3
- boootstrap table applied
> discuss3 thread for bs3

- trunk/web/template/bs3/problem.php
> resize the bs3 submit window

- trunk/web/admin/problem_add_page.php
> 题目添加时候，预览开关

- trunk/web/admin/index.php
> 应对新的menu做出的调整index.php

- trunk/web/admin/admin.css
> 更新menu2.php的CSS样式

- README.md
- trunk/web/group_statistics.php
- trunk/web/include/bbcode.php
- trunk/web/template/bs3/group_statistics.php
- trunk/web/template/syzoj/group_statistics.php
> Group statistics

- trunk/web/template/syzoj/ranklist.php
The ranking page is more aesthetically pleasing
Add full language translations and small button styles to the day, week, month, and year in the upper left corner
> The ranking page is more aesthetically pleasing

- trunk/web/template/syzoj/index.php
给syzoj主题的index.php增加轮播图功能
不是很成熟 最好修改后在在使用
> 给syzoj主题的index.php增加轮播图功能

- trunk/web/lang/ko.php
Synchronized to cn.php
Thank you :)
> ko.php synchronized to cn.php

- trunk/web/admin/problem_list.php
- Adjust the table cell merging to fit the table data.
> Adjust the table cell merging

- trunk/web/template/bs3/ranklist.php
bs3 ranklist fix
: group name table head
> bs3 ranklist fix
